version: "3"
services:
  db:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "Password1234"
        ACCEPT_EULA: "Y"

  web:
    build: ./Gavinhow.SpotifyStatistics.Web/publish
    restart: on-failure
    depends_on:
      - db
    ports:
     - "8080:80"

  backend:
    build: ./Gavinhow.SpotifyStatistics.Backend/publish
    restart: on-failure
    depends_on:
      - db
