// <auto-generated />
using System;
using Gavinhow.SpotifyStatistics.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gavinhow.SpotifyStatistics.Database.Migrations
{
    [DbContext(typeof(SpotifyStatisticsContext))]
    [Migration("20200704205523_AddFriendsTable")]
    partial class AddFriendsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SpotifyTracker")
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.ArtistAlbum", b =>
            {
                b.Property<string>("AlbumId");

                b.Property<string>("ArtistId");

                    b.HasKey("AlbumId", "ArtistId");

                    b.ToTable("ArtistAlbums");
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.ArtistTrack", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrackId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("ArtistId", "TrackId");

                    b.ToTable("ArtistTracks");
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.Friend", b =>
            {
                b.Property<string>("UserId");

                b.Property<string>("FriendId");

                b.Property<DateTime>("Created");

                b.Property<DateTime>("Modified");

                    b.HasKey("UserId", "FriendId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.Play", b =>
            {
                b.Property<string>("TrackId");

                b.Property<DateTime>("TimeOfPlay");

                b.Property<string>("UserId");

                b.Property<DateTime>("Created");

                b.Property<DateTime>("Modified");

                    b.HasKey("TrackId", "TimeOfPlay", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.Track", b =>
            {
                b.Property<string>("Id");

                b.Property<string>("AlbumId");

                b.Property<DateTime>("Created");

                b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.User", b =>
            {
                b.Property<string>("Id");

                b.Property<string>("AccessToken");

                b.Property<DateTime>("Created");

                b.Property<string>("DisplayName");

                b.Property<double>("ExpiresIn");

                b.Property<DateTime>("Modified");

                b.Property<string>("RefreshToken");

                b.Property<DateTime>("TokenCreateDate");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.Friend", b =>
                {
                    b.HasOne("Gavinhow.SpotifyStatistics.Database.Entity.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gavinhow.SpotifyStatistics.Database.Entity.Play", b =>
                {
                    b.HasOne("Gavinhow.SpotifyStatistics.Database.Entity.User", "User")
                        .WithMany("Plays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
