name: CI/CD Backend
on:
  push:
    paths:
      - 'Services/Gavinhow.SpotifyStatistics.Web/**'
      - 'Services/Gavinhow.SpotifyStatistics.Api/**'
      - 'Services/Gavinhow.SpotifyStatistics.Database/**'
      - 'Services/Gavinhow.SpotifyStatistics.Database.Entity/**'
      - 'infrastructure/**/backend/**'
      - 'infrastructure/**/backend_azure/**'
      - '.github/workflows/backend.yml'
    branches:
      - main
      - feature/backend-dev

  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build ./Services/Gavinhow.SpotifyStatistics.Web/Gavinhow.SpotifyStatistics.Web.csproj --configuration Release --output ./publish_output
      - uses: actions/upload-artifact@v3
        with:
          name: spotify_statistics_web
          path: './publish_output/'
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: terraform
          path: './infrastructure/'
          if-no-files-found: error