name: CI/CD Backend
on:
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build ./Services/Gavinhow.SpotifyStatistics.Web/Gavinhow.SpotifyStatistics.Web.csproj --configuration Release --output ./publish_output
      - uses: actions/upload-artifact@v4
        with:
          name: spotify_statistics_web
          path: './publish_output/'
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: terraform
          path: './infrastructure/'
          if-no-files-found: error

  develop:
    name: 'Deploy'
    needs: [ build ]
    uses: ./.github/workflows/backend-deploy.yml
    with:
      environment: develop
      tf_working_dir: './infrastructure/live/dev/backend'
    secrets: inherit