name: 'Function App Deploy'
on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      tf_version:
        description: 'The version of Terraform to use'
        required: false
        default: 'latest'
        type: string
      tg_version:
        description: 'The version of Terragrunt to use'
        required: false
        default: 'latest'
        type: string
      tf_working_dir:
        description: 'The working directory for Terraform'
        required: true
        type: string



jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_postgres_connection: ${{ secrets.POSTGRES_CONNECTION }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_INPUT: false
      ARM_USE_CLI: false
      TERRAGRUNT_AUTO_INIT: false
      TERRAGRUNT_LOG_LEVEL: error
    steps:
      # Terraform deployment
      - uses: actions/download-artifact@v3
        with:
          name: terraform
          path: ./infrastructure
      - name: 'Init'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ inputs.tf_version }}
          tg_actions_version: ${{ inputs.tg_version }}
          tf_actions_binary: "terragrunt"
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ inputs.tf_working_dir }}
      - name: 'Apply'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ inputs.tf_version }}
          tg_actions_version: ${{ inputs.tg_version }}
          tf_actions_binary: "terragrunt"
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ inputs.tf_working_dir }}
      - name: 'Output'
        id: output
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ inputs.tf_version }}
          tg_actions_version: ${{ inputs.tg_version }}
          tf_actions_binary: "terragrunt"
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: ${{ inputs.tf_working_dir }}

      - name: Set Function App name as Environment Variable
        run: |
          echo "FUNCTION_APP_NAME=${{ fromJson(steps.output.outputs.tf_actions_output).import_function_app_name.value }}" >> $GITHUB_ENV
          echo "FUNCTION_APP_RESOURCE_GROUP=${{ fromJson(steps.output.outputs.tf_actions_output).import_function_app_resource_group_name.value }}" >> $GITHUB_ENV
        id: getPublishProfile


      # Function App Deployment
      - uses: actions/download-artifact@v3
        with:
          name: import_function_app
          path: ./function_app

      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      - name: Get Publish Profile
        run: |
          echo "PUBLISH_PROFILE=$(az webapp deployment list-publishing-profiles -g '${{ env.function_app_resource_group }}' -n '${{ env.function_app_name }}' --xml)" >> $GITHUB_OUTPUT
        id: getPublishProfile

      - name: 'Deploy Function App to Azure'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.function_app_name }}
          package: './function_app'
          publish-profile: ${{ steps.getPublishProfile.outputs.PUBLISH_PROFILE }}