name: 'Function App Deploy'
on:
  workflow_call:

jobs:
  develop:
    name: 'Develop'
    uses: ./.github/workflows/function_app-deploy.yml
    with:
      environment: develop
      tf_working_dir: './infrastructure/live/dev'
    secrets: inherit
  production:
    name: 'Production'
    needs: [ develop ]
    uses: ./.github/workflows/function_app-deploy.yml
    with:
      environment: production
      tf_working_dir: './infrastructure/live/prod'
    secrets: inherit
