name: CI

on:
  push:
    branches:
      - main
      - feature/terraform

env:
  tf_version: 'latest'
  tg_version: 'latest'
  TERRAGRUNT_AUTO_INIT: 'false'
  TF_INPUT: false
  ARM_USE_CLI: false

jobs:
  validate_terragrunt:
    name: Validate Terragrunt
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: develop
      tf_working_dir: './infrastructure/live/dev'
    secrets: inherit

  develop:
    name: Deploy Develop Terraform
    needs: validate_terragrunt
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: develop
      tf_working_dir: './infrastructure/live/dev'
    secrets: inherit